version: '3'
services:
  app:
    container_name: app
    build: .
    depends_on:
      - ddb
      - redis
    ports:
      - "5000:80"
    env_file:
      - .env
    volumes:
      - "./static:/app/app/static/"

  ddb:
    container_name: ddb
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes:
     - ./data/ddb:/home/dynamodblocal/data
    ports:
        - "8000:8000"
  
  redis:
    container_name: redis
    image: redis:5

  statsd:
    container_name: statsd
    image: graphiteapp/graphite-statsd

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "9000:3000"